export const TREAR_POSTS ='traer_posts';
export const CARGANDO = 'cargando';
export const USER_STATE ='user_state';
export const CERRAR_SESION = 'cerrar_sesion';
export const ERROR = 'error';
export const CAMBIO_TEXTO_COMENTARIO = 'cambio_texto_comentario';
export const CAMBIO_STATUS_COMENTARIO = 'cambio_status_comentario';
export const PUBLICAR_COMENTARIO = 'publicar_comentario';
export const ELIMINAR_COMENTARIO = 'eliminar_comentario';